### ISSUE TITLE
Cannot change option Turn on printer with - unknown plug

### ISSUE THREAD

**Issue by FrancYescO** [fieldOfView/Cura-OctoPrintPlugin#232]
Hello i was using both PSU Control, and Tuya Smarplug plugin on my octoprint instance, the tuya plugin was unstable so i totally removed the plugin from octoprint, i never figure out how to set the plugin to turn on via PSU Control as both options in the selectbox are disabled and i have no possibility to change, it automatically select the last option (that actually i assume is the unistalled tuya smartplug plugin)

<img width="310" alt="image" src="https://user-images.githubusercontent.com/4574593/116856149-ec537c00-abfa-11eb-87bb-7a56f228e8c1.png">

**Comment by FrancYescO** [comment]
i've solved by going to (MacOS)`/Users/user/Library/Application\ Support/cura/4.9/machine_instances/myprinter.cfg` and removing the line `octoprint_power_plug = tuyasmartplug/3D Printer/192.168.1.103` after the restart finally the `Unknown plug` option disappeared and i'm able to select PSU Control

but i think this should be considered a bug.

**Comment by melyux** [comment]
I had this problem too. When you change the OctoPrint's IP address in Cura, it should update the `octoprint_power_plug` line as well. It only changes the OctoPrint address, but `octoprint_power_plug` is left with the old IP address, causing this bug.

**Comment by fieldOfView** [comment]
Sofar I've only seen this reported by Mac OS users. I'll get this fixed in the next release.

**Comment by fieldOfView** [comment]
This looks like a MacOS specific issue in Qt: https://forum.qt.io/topic/123101/quick-controls-1-combobox-items-unselectable-on-macos

Unfortunately the fix (changing the controls to QtQuick 2) means that the dropdown will look ugly and be unreadable on current Mac OS systems (possibly limited to M1, but I am not sure of that).

Stuck between a rock and a hard place...
I'll keep looking for solutions.

**Comment by fieldOfView** [comment]
Can you check if this is still an issue with Cura 5? This post has a prerelease of the OctoPrint Connection plugin:
https://community.ultimaker.com/topic/40313-fieldofview-plugins-for-cura-50/

**Comment by melyux** [comment]
Still happening in the latest Cura 5. Not the unselectable thing, but the thing where every time you start Cura, this line

```
octoprint_power_plug = tasmota/Printer Power/192.168.1.100/1
```

is populated with the old IP address, and changing it or deleting the line doesn't help. The next time you start Cura, it goes back to the old, wrong value, and Tasmota control doesn't work.
